format_version: 3
pipelines:
  default-crash-move-folder:
    group: defaultGroup
    template: mytemplate
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      default-cmf:
        scm: 4a8cf7af-9170-4379-bb84-7b75a204118c
        destination: default-cmf
      mapy-controller:
        scm: 7b37b961-6310-45e4-9968-25a17397b6a3
        destination: mapy-controller
