format_version: 3
pipelines:
  default-crash-move-folder:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      default-cmf:
        scm: 4a8cf7af-9170-4379-bb84-7b75a204118c
        destination: default-cmf
      mapy-controller:
        scm: 7b37b961-6310-45e4-9968-25a17397b6a3
        destination: mapy-controller
    stages:
      - name: stage-pull-test-and-deploy
        fetch_materials: true
        clean_working_directory: false
        never_cleanup_artifacts: true
        approval:
          type: success
          authorization:
            roles: []
            users: []
        environment_variables: []
        jobs:
          - name: job-pull-test-and-deploy
            run_instance_count: 
            timeout: 
            environment_variables: []
            resources: []
            tasks:
              - type: exec
                attributes:
                  run_if:
                  - passed
                  command: pwd
                  args: ''
