format_version: 9
common:
  testing_stages: &testing_stages
    - stage-pull-and-test:
        resources:
          - hq
          - windows
          - arcmap10-6
        tasks:
          - exec:
              command: git
              arguments:
              - "-C"
              - default-cmf
              - lfs
              - pull
          - exec:
              command: cmd
              arguments:
                - "/c"
                - "C:/py27arcgis106/ArcGIS10.6/python.exe"
                - "-m"
                - virtualenv
                - env
          - exec:
              command: "env/Scripts/python.exe"
              arguments:
              - "-m"
              - pip
              - install
              - "-e"
              - mapy-controller
          - exec:
              command: "env/Scripts/python.exe"
              arguments:
              - "-m"
              - mapactionpy_controller.check_naming_convention
              - default-cmf/20YYiso3nn/cmf_description.json

pipelines:
  test-default-cmf-PRs:
    group: Default-CMF-Group
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      default-cmf:
        scm: 4a8cf7af-9170-4379-bb84-7b75a204118c
        destination: default-cmf
      mapy-controller:
        git: https://github.com/mapaction/mapactionpy_controller.git
        destination: mapy-controller
        branch: master
        username: mapaction-ci-servers
        encrypted_password : AES:/tL+kSfanw1Vz+YhfX+C7g==:3UFicQJU9iJAH7ITgi/0MsBRs0Al81OIIkwq9Qru0NPsuXsTT+tFOtKAf4JhZXI7
    stages:
      - *testing_stages

  test-controller-PRs:
    group: Default-CMF-Group
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      default-cmf:
        git: https://github.com/mapaction/default-crash-move-folder.git
        destination: default-cmf
        branch: master
        username: mapaction-ci-servers
        encrypted_password : AES:/tL+kSfanw1Vz+YhfX+C7g==:3UFicQJU9iJAH7ITgi/0MsBRs0Al81OIIkwq9Qru0NPsuXsTT+tFOtKAf4JhZXI7
      mapy-controller:
        scm: 7b37b961-6310-45e4-9968-25a17397b6a3
        destination: mapy-controller
    stages:
      - *testing_stages

  test-PRs-in-combination:
    group: Default-CMF-Group
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      default-cmf:
        scm: 4a8cf7af-9170-4379-bb84-7b75a204118c
        destination: default-cmf
      mapy-controller:
        scm: 7b37b961-6310-45e4-9968-25a17397b6a3
        destination: mapy-controller
    stages:
      - *testing_stages


  test-and-deploy-master-branches-only:
    group: Default-CMF-Group
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      default-cmf:
        git: https://github.com/mapaction/default-crash-move-folder.git
        destination: default-cmf
        branch: master
        username: mapaction-ci-servers
        encrypted_password : AES:/tL+kSfanw1Vz+YhfX+C7g==:3UFicQJU9iJAH7ITgi/0MsBRs0Al81OIIkwq9Qru0NPsuXsTT+tFOtKAf4JhZXI7
      mapy-controller:
        git: https://github.com/mapaction/mapactionpy_controller.git
        destination: mapy-controller
        branch: master
    stages:
      - *testing_stages
      - deploy:
          resources:
            - hq
            - windows
          tasks:
            - exec:
                command: robocopy
                arguments:
                - "/mir"
                - default-cmf
                - \\192.168.106.24\SYSAdmin\testing\github-mirror\default-cmf


# - name: clone-to-ftp
#   fetch_materials: true
#   clean_working_directory: false
#   never_cleanup_artifacts: false
#   approval:
#     type: success
#     authorization:
#       roles: []
#       users: []
#   environment_variables: []
