format_version: 9
pipelines:
  default-crash-move-folder2:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      default-cmf:
        scm: 4a8cf7af-9170-4379-bb84-7b75a204118c
        destination: default-cmf
      mapy-controller:
        scm: 7b37b961-6310-45e4-9968-25a17397b6a3
        destination: mapy-controller
    stages:
      - stage-pull-test-and-deploy:
          jobs:
            job-pull-test-and-deploy:
              tasks:
                - exec:
                    command: pwd
                - exec:
                    command: ls
                - exec:
                    command: git
                    arguments:
                    - "-C"
                    - default-cmf
                    - lfs
                    - pull
                - exec:
                    command: echo
                    arguments:
                    - "$GO_SCM_DEFAULT_CMF_PR_BRANCH"
                - exec:
                    command: virtualenv
                    arguments:
                      - "--python=python3"
                      - env


#     - type: exec
#       attributes:
#         run_if:
#         - passed
#         command: pwd
#         args: ''
#     - type: exec
#       attributes:
#         run_if: []
#         command: ls
#         args: ''
#     - type: exec
#       attributes:
#         run_if:
#         - passed
#         command: virtualenv
#         arguments:
#         - "--python=python3"
#         - env
#     - type: exec
#       attributes:
#         run_if:
#         - passed
#         command: "./env/bin/python3"
#         arguments:
#         - "-m"
#         - pip
#         - install
#         - "-e"
#         - mapy-controller
#     - type: exec
#       attributes:
#         run_if:
#         - passed
#         command: "./env/bin/python3"
#         arguments:
#         - "-m"
#         - mapactionpy_controller.check_naming_convention
#         - default-cmf/20YYiso3nn/cmf_description.json
#     - type: exec
#       attributes:
#         run_if:
#         - passed
#         command: ls
#         arguments:
#         - "-l"
#         - "/var/lib/go-agent/pipelines/default-crash-move-folder/default-cmf/20YYiso3nn/Operations/Travel/MapAction_Team_Movements_Log.xlsx"
#     tabs: []
#     artifacts: []
# - name: clone-to-ftp
#   fetch_materials: true
#   clean_working_directory: false
#   never_cleanup_artifacts: false
#   approval:
#     type: success
#     authorization:
#       roles: []
#       users: []
#   environment_variables: []
#   jobs:
#   - name: clone-script
#     run_instance_count: 
#     timeout: 
#     environment_variables:
#     - secure: true
#       name: LFTP_PASSWORD
#       encrypted_value: AES:MqCuCm+56dnVR0ugNM5uaA==:4pO/g3WlyMcI4V5NMVdeM/93Ez2Fj/BiAtft2dFCIzU7Kq8Gg4DMvm3/54B7QROf
#     resources: []
#     tasks:
#     - type: exec
#       attributes:
#         run_if: []
#         command: pwd
#         args: ''
#     - type: exec
#       attributes:
#         run_if: []
#         command: echo
#         arguments:
#         - "$LFTP_PASSWORD"
#     - type: exec
#       attributes:
#         run_if:
#         - passed
#         command: lftp
#         arguments:
#         - "-f"
#         - default-cmf/deploy-via-ftp-server.lftp.txt
#     - type: exec
#       attributes:
#         run_if:
#         - passed
#         command: ls
#         arguments:
#         - "-l"
#         - "/var/lib/go-agent/pipelines/default-crash-move-folder/default-cmf/20YYiso3nn/Operations/Travel/MapAction_Team_Movements_Log.xlsx"
#     tabs: []
#     artifacts:
#     - type: build
#       source: "*"
#       destination: ''
