# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# convert_raster_raainfail_vector_3day.py
# Created on: 2021-12-22 13:56:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
wrl_evnt_rai_ras_s0_wmo_pp_3day20211219_tif = "wrl_evnt_rai_ras_s0_wmo_pp_3day20211219.tif"
phl_admn_ad0_py_s0_namria_pp_country_shp = "G:\\Shared drives\\country-responses\\2021\\2021-phl-001\\GIS\\2_Active_Data\\202_admn\\phl_admn_ad0_py_s0_namria_pp_country.shp"
phl_evnt_rai_ras_s0_wmo_pp_3day20211219_tif = "G:\\Shared drives\\country-responses\\2021\\2021-phl-001\\GIS\\2_Active_Data\\213_evnt\\phl_evnt_rai_ras_s0_wmo_pp_3day20211219.tif"
phl_evnt_rai_py_s0_wmo_pp_3day20211219_shp = "G:\\Shared drives\\country-responses\\2021\\2021-phl-001\\GIS\\2_Active_Data\\213_evnt\\phl_evnt_rai_py_s0_wmo_pp_3day20211219.shp"

# Process: Clip
arcpy.Clip_management(wrl_evnt_rai_ras_s0_wmo_pp_3day20211219_tif, "114.277892253 4.58729449700004 126.604965596 21.1218854790001", phl_evnt_rai_ras_s0_wmo_pp_3day20211219_tif, phl_admn_ad0_py_s0_namria_pp_country_shp, "65536", "NONE", "NO_MAINTAIN_EXTENT")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(phl_evnt_rai_ras_s0_wmo_pp_3day20211219_tif, phl_evnt_rai_py_s0_wmo_pp_3day20211219_shp, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")

